version: '3.7'

services:
  s-pipes-editor-rest:
    image: 'chlupnoha/s-pipes-editor-rest:latest'
    container_name: s-pipes-editor-rest
    ports:
      - '18115:18115'
    expose:
      - "18115"
    networks:
      - overlay
    depends_on:
      - s-pipes-engine
      - rdf4j
    environment:
      - SCRIPTPATHS=/home/jordan/IdeaProjects/s-pipes-newgen/src/test/resources/scripts_test/sample
      - ENGINEURL=http://s-pipes-engine:8080/s-pipes/
      - SCRIPTRULES=/home/jordan/IdeaProjects/s-pipes-newgen/src/main/resources/rules
      - RDF4J_REPOSITORYURL=http://rdf4j:8080/rdf4j-server/repositories
      - RDF4J_REPOSITORYNAME=s-pipes-hello-world
      - RDF4J_PCONFIGURL=/home/jordan/IdeaProjects/s-pipes-newgen/src/main/resources/config.ttl
    volumes:
      - /tmp:/tmp
      - /home:/home
      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/

  s-pipes-engine:
    image: 'chlupnoha/spipes-engine:latest'
    container_name: s-pipes-engine
    ports:
      - "8081:8080"
    expose:
      - "8081"
    networks:
      - overlay
    depends_on:
      - rdf4j
    environment:
      - CONTEXTS_SCRIPTPATHS=/home/jordan/IdeaProjects/s-pipes-newgen/src/test/resources/scripts_test/sample
    volumes:
      - /tmp:/tmp
      - /home:/home
      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/

  rdf4j:
    image: 'eclipse/rdf4j-workbench:amd64-3.5.0'
    container_name: rdf4j
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - overlay
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g
    volumes:
      - data:/var/rdf4j
      - logs:/usr/local/tomcat/logs

volumes:
  data:
  logs:

networks:
  overlay:

